import json
import base64
import os

SECRETS_FILE = os.path.join(os.path.dirname(__file__), "../secrets.json")
OUTPUT_FILE  = os.path.join(os.path.dirname(__file__), "../main/secrets.h")

with open(SECRETS_FILE) as f:
    s = json.load(f)

# Validate
required = ["client_id", "client_secret", "redirect_uri", "wifi_ssid", "wifi_pass"]
for key in required:
    if not s.get(key):
        raise ValueError(f"Missing required field '{key}' in secrets.json")

# Precompute Base64 for the C file so it doesn't have to at runtime
credentials_b64 = base64.b64encode(
    f"{s['client_id']}:{s['client_secret']}".encode()
).decode()

header = f"""
/* Auto-generated by generate_secrets.py — DO NOT COMMIT */
#pragma once

#define SPOTIFY_CLIENT_ID       "{s['client_id']}"
#define SPOTIFY_CLIENT_SECRET   "{s['client_secret']}"
#define SPOTIFY_CLIENT_B64      "{credentials_b64}"
#define SPOTIFY_REDIRECT_URI    "{s['redirect_uri']}"
#define SPOTIFY_REFRESH_TOKEN   "{s.get('refresh_token', '')}"
#define WIFI_SSID               "{s['wifi_ssid']}"
#define WIFI_PASS               "{s['wifi_pass']}"
""".lstrip()

with open(OUTPUT_FILE, "w") as f:
    f.write(header)

print(f"✅ Generated {OUTPUT_FILE}")